vich_uploader:
    db_driver: orm

    mappings:
        gpxFiles:
            uri_prefix: /gpxFiles
            upload_destination: '%kernel.project_dir%/public/gpxFiles'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
